version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-11-06T23-17-07Z
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: eu-west-1
    ports:
      - 9000:9000
    command: server /data
  fake-gcs:
    image: fsouza/fake-gcs-server:1.18.3
    ports:
      - 4443:4443
    command: -public-host localhost -scheme http
  sftp:
    image: atmoz/sftp:alpine
    ports:
    - "22:22"
    command: foo:pass:::sftp_test bar:pass:::plugin_test
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
    - "10000:10000"
    command: azurite-blob --blobHost 0.0.0.0
  configure-buckets:
    image: minio/mc:RELEASE.2020-10-03T02-54-56Z
    entrypoint: sh
    depends_on:
      - minio
    command:
      - -c
      - |
        sleep 2 &&
        mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY &&
        mc admin user add minio foo barbarbar &&
        echo '{"Version": "2012-10-17", "Statement": [{"Action": ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:CreateBucket", "s3:DeleteBucket"], "Effect": "Allow", "Resource": ["arn:aws:s3:::s3-round-trip-with-role/*", "arn:aws:s3:::s3-round-trip-with-role"], "Sid": ""}]}' > /tmp/policy.json &&
        mc admin policy add minio userpolicy /tmp/policy.json &&
        mc admin policy set minio userpolicy user=foo
